sudo: required
services:
  - docker

before_install:
  - docker build -t yannicksealy/docker-frontend -f Dockerfile.dev .

script:
  - docker run yannicksealy/docker-frontend npm run test -- --coverage